name: Search cye04720 across archives (separated Python)

on:
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make scripts executable
        run: |
          chmod +x scripts/*.py

      - name: Generate candidate URLs
        env:
          EMAIL: cye04720@nifty.com
        run: |
          python scripts/generate_candidates.py --email "${EMAIL}" --out candidates.txt
          echo "=== Candidates (head) ==="
          head -n 50 candidates.txt || true

      - name: Check archives for email
        env:
          EMAIL: cye04720@nifty.com
        run: |
          python scripts/check_archives.py --email "${EMAIL}" --candidates candidates.txt --out found_archives.txt

      - name: Show results
        if: always()
        run: |
          echo "=== Found archive snapshots ==="
          if [ -s found_archives.txt ]; then
            sort -u found_archives.txt | tee found_archives.txt
          else
            echo "No results found in this run."
          fi

      - name: Upload results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: found-archives
          path: found_archives.txt
